### ISSUE TITLE
Cannot compile in Android 6.0 (API 23)

### ISSUE THREAD

**Issue by PietroDev** [klinker41/android-smsmms#40]
http://developer.android.com/sdk/api_diff/23/changes/changes-summary.html

All org.apache.http.* classes have been removed. Cannot compile with android-23, maybe it will neither work on a API 23 device?

**Comment by KimKyung-man** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

gracefulife@naver.com 님께 보내신 메일 <[android-smsmms] Cannot compile in Android 6.0 (API 23) (#40)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by klinker41** [comment]
You'll need this and it works fine:
https://developer.android.com/preview/behavior-changes.html#behavior-apache-http-client

**Comment by KimKyung-man** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

gracefulife@naver.com 님께 보내신 메일 <Re: [android-smsmms] Cannot compile in Android 6.0 (API 23) (#40)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by PietroDev** [comment]
Thanks!
And sorry I dint' see this link before.

**Comment by klinker41** [comment]
No problem, thanks for being on top of things. It had me a little worried
yesterday afternoon before I found that.

**Comment by PietroDev** [comment]
I reopen this issue because I tried with the fix and, while the LVL project (which had the same problem) now compiles, I have still errors on this one:

src\main\java\com\android\mms\service\http\NetworkAwareHttpClient.java:140: error: cannot
 find symbol
                SSLCertificateSocketFactory.getHttpSocketFactory(
                                           ^
  symbol:   method getHttpSocketFactory(int,SSLSessionCache)
  location: class SSLCertificateSocketFactory

The class is in the android.net package and it seems the method now is missing, the problematic line is:

```java
schemeRegistry.register(new Scheme("https", SSLCertificateSocketFactory.getHttpSocketFactory(SOCKET_OPERATION_TIMEOUT, sessionCache), 443));
```

**Comment by klinker41** [comment]
Looks like we'll need to update the MMS Service that I've merged into the library and modified slightly, starting in 5.1 they've moved away from using apache http which is what we need for this to work correctly.

https://github.com/CyanogenMod/android_packages_services_Mms/tree/cm-12.1

I'll try and find time before the full release of Marshmallow, not sure how much work it will end up being.

**Comment by PietroDev** [comment]
Just as a final add:
If I add the legacy library it compiles but then proguard fails (errors about duplicate classes).
Proguard does not fail using the legacy library with other projects.
So I will not be usning android-22 until the final release

**Comment by klinker41** [comment]
Most of the changes are now finished, you can read about updating over here: https://github.com/klinker41/android-smsmms/blob/master/upgrading_for_marshmallow.md.

Not quite done with ensuring everything is backwards compatible yet, there are some multi sim things that I still need to do that will probably cause it to crash on Android 5.0. Devices below Android 5.0 should not have had any functionality changed but I still need to test that as well.
